image:
  repository: nginx

ports:
  - name: http
    containerPort: 80
    protocol: TCP

ingress:
  enabled: true

# it doesn't matter if you add quotes or not, the quotes will be added in the final yaml anyway
envVars:
  FOO: "bar"
  BOO: far